export enum DeviceType {
  SENSOR = 'SENSOR',
  GATEWAY = 'GATEWAY',
  METER = 'METER',
  ACTUATOR = 'ACTUATOR',
  CAMERA = 'CAMERA',
  CONTROLLER = 'CONTROLLER',
  SMARTLOCK = 'SMARTLOCK',
  SMARTHAT = 'SMARTHAT'
}

export enum DeviceStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum BrokerType {
  VERNEMQ = 'VERNEMQ',
  AWS_IOT = 'AWS_IOT',
  AZURE_IOT = 'AZURE_IOT',
}

export enum CredentialStatus {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
  ROTATED = 'ROTATED',
  EXPIRED = 'EXPIRED',
}

export enum CodecType {
  JSON = 'JSON',
  PROTOBUF = 'PROTOBUF',
  CBOR = 'CBOR',
  HEX_BINARY = 'HEX_BINARY',
}

export enum AuditAction {
  DEVICE_REGISTERED = 'DEVICE_REGISTERED',
  DEVICE_UPDATED = 'DEVICE_UPDATED',
  DEVICE_DECOMMISSIONED = 'DEVICE_DECOMMISSIONED',
  CREDENTIAL_ISSUED = 'CREDENTIAL_ISSUED',
  CREDENTIAL_ROTATED = 'CREDENTIAL_ROTATED',
  CREDENTIAL_REVOKED = 'CREDENTIAL_REVOKED',
  ASSIGNED = 'ASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  CONFIG_UPDATED = 'CONFIG_UPDATED',
  TAXONOMY_CHANGED = 'TAXONOMY_CHANGED',
  NODE_CHANGED = 'NODE_CHANGED',
  STATUS_CHANGED = 'STATUS_CHANGED',
}

export enum ActorType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  SERVICE = 'SERVICE',
}

export enum ConnectivityStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE'
}
